version: "3.8"
services:
  application:
    container_name: remote-debugging-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - GIN_MODE=release
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge